# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - wiki/**
      - .github/workflows/dotnet.yml
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          2.2.x
          3.1.x
          5.0.x
          6.0.x
          7.0.x
          8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Run benchmark
      run: dotnet ./AsyncAwaitCosts.ConsoleAppBenchmark/bin/Release/netcoreapp2.2/AsyncAwaitCosts.ConsoleAppBenchmark.dll
    - name: Copy artifacts to wiki
      run: cp -r ./BenchmarkDotNet.Artifacts/results/*github.md ./wiki/
    - name: Push wiki
      uses: Andrew-Chen-Wang/github-wiki-action@v4
      
